### ISSUE TITLE
Droppe score-dict i Game, heller returnere antall klarerte linjer

### ISSUE THREAD

**Issue by erlendb** [erlendb/Tetris#2]

**Comment by bjornksa** [comment]
Spørs hvor avansert tetris vi vil ha. Vanlig tetris gir høyere score for å fjerne flere linjer om ganger, og høyere score senere i spillet. Veldig lite viktig for AI-en, så kan godt droppes

**Comment by erlendb** [comment]
Tenker at dette henger litt sammen med #3 .
Altså ikke tenke på score inni tetris.Game i det hele tatt, men behandle det på utsiden. For oss så er jo ikke den "vanlige" scoren så aktuell uansett? Siden vi antakelig skal ta flere parametre i betraktning for å bestemme hvor bra en brikkeplassering er

**Comment by erlendb** [comment]
done
